version: '3.0'

 

services:
  reportservice:
    image: report:latest
    ports:
      - "4000:80"
    networks:
      - backend

 

  customerservice:
    image: customer:latest
    ports:
      - "5000:80"
    networks:
      - backend
networks:
  backend: